http:
  routers:
    relution:
      rule: Host(`external.url`)
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: relution

  services:
    relution:
      loadBalancer:
        servers:
          - url: "http://relution:8080"