http:
  routers:
    relution:
      rule: Host(`external.url`)
      entryPoints:
        - websecure
      tls: {}
      service: relution

  services:
    relution:
      loadBalancer:
        servers:
          - url: "http://relution:8080"

tls:
  certificates:
    - certFile: "/opt/certs/server.pem"
      keyFile: "/opt/certs/server.key"
